# -*- coding: utf-8 -*-
"""Hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nKmcnjF2aJN1eFqPwXCwFLpRodPRW24K
"""

print("Hello")